export const CATEGORIES = {
  FOOD: 'FOOD',
  TRAVEL: 'TRAVEL',
  SALARY: 'SALARY',
  SHOP: 'SHOP',
  HOME: 'HOME',
  TRANSPORT: 'TRANSPORT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  UTILITIES: 'UTILITIES',
  HEALTH: 'HEALTH',
  BUSINESS: 'BUSINESS',
  INVESTMENT: 'INVESTMENT',
  OTHER: 'OTHER',
} as const

export type CategoryKey = keyof typeof CATEGORIES;